-- First, delete the English transliteration Hebrew names I just added
DELETE FROM public.names WHERE language = 'he' AND region = 'IL';

-- Now insert proper Hebrew names with Hebrew characters
INSERT INTO public.names (name, gender, origin, meaning, language, region, is_active, created_at)
VALUES 
  -- Hebrew boys names with Hebrew characters
  ('דוד', 'male', 'עברית', 'אהוב', 'he', 'IL', true, now()),
  ('דניאל', 'male', 'עברית', 'אלוהים הוא השופט שלי', 'he', 'IL', true, now()),
  ('מיכאל', 'male', 'עברית', 'מי כמוני אלוהים', 'he', 'IL', true, now()),
  ('יהונתן', 'male', 'עברית', 'אלוהים נתן', 'he', 'IL', true, now()),
  ('יהושע', 'male', 'עברית', 'אלוהים הוא ישועה', 'he', 'IL', true, now()),
  ('אהרון', 'male', 'עברית', 'הר גבוה', 'he', 'IL', true, now()),
  ('בנימין', 'male', 'עברית', 'בן יד ימין', 'he', 'IL', true, now()),
  ('שמואל', 'male', 'עברית', 'נשמע על ידי אלוהים', 'he', 'IL', true, now()),
  ('יצחק', 'male', 'עברית', 'צחוק', 'he', 'IL', true, now()),
  ('נח', 'male', 'עברית', 'מנוחה, נחמה', 'he', 'IL', true, now()),
  ('טי', 'male', 'עברית', 'טל', 'he', 'IL', true, now()),
  ('טהר', 'male', 'עברית', 'טוהר', 'he', 'IL', true, now()),
  ('טובי', 'male', 'עברית', 'טוב', 'he', 'IL', true, now()),
  ('טוביה', 'male', 'עברית', 'אלוהים טוב', 'he', 'IL', true, now()),
  ('טוהר', 'male', 'עברית', 'טוהר', 'he', 'IL', true, now()),
  ('תום', 'male', 'עברית', 'תמים', 'he', 'IL', true, now()),
  ('טמי', 'male', 'עברית', 'תמים', 'he', 'IL', true, now()),
  ('תים', 'male', 'עברית', 'שלמות', 'he', 'IL', true, now()),
  ('תימור', 'male', 'עברית', 'גבוה', 'he', 'IL', true, now()),
  ('טל', 'male', 'עברית', 'טל', 'he', 'IL', true, now()),
  ('טלאור', 'male', 'עברית', 'טל אור', 'he', 'IL', true, now()),
  ('תמיר', 'male', 'עברית', 'נסתר', 'he', 'IL', true, now()),
  ('יאיר', 'male', 'עברית', 'הוא יאיר', 'he', 'IL', true, now()),
  ('יאן', 'male', 'עברית', 'מתנת אלוהים', 'he', 'IL', true, now()),
  ('יער', 'male', 'עברית', 'יער', 'he', 'IL', true, now()),
  ('אדם', 'male', 'עברית', 'אדם, אדמה', 'he', 'IL', true, now()),
  ('אילן', 'male', 'עברית', 'עץ', 'he', 'IL', true, now()),
  ('אדיל', 'male', 'עברית', 'אציל', 'he', 'IL', true, now()),
  ('אור', 'male', 'עברית', 'אור', 'he', 'IL', true, now()),
  ('אורי', 'male', 'עברית', 'האור שלי', 'he', 'IL', true, now()),
  ('עמית', 'male', 'עברית', 'ידיד', 'he', 'IL', true, now()),
  ('אריאל', 'male', 'עברית', 'אריה של אלוהים', 'he', 'IL', true, now()),
  ('אבי', 'male', 'עברית', 'אבי', 'he', 'IL', true, now()),
  ('אלי', 'male', 'עברית', 'האלוהים שלי', 'he', 'IL', true, now()),
  ('גל', 'male', 'עברית', 'גל', 'he', 'IL', true, now()),
  ('גיל', 'male', 'עברית', 'שמחה', 'he', 'IL', true, now()),
  ('עומר', 'male', 'עברית', 'אלומה', 'he', 'IL', true, now()),
  ('יובל', 'male', 'עברית', 'נחל', 'he', 'IL', true, now()),
  ('אגם', 'male', 'עברית', 'אגם', 'he', 'IL', true, now()),
  ('אדיר', 'male', 'עברית', 'אדיר', 'he', 'IL', true, now()),
  ('אדר', 'male', 'עברית', 'אדר', 'he', 'IL', true, now()),
  ('אוהד', 'male', 'עברית', 'אוהד', 'he', 'IL', true, now()),
  ('דור', 'male', 'עברית', 'דור', 'he', 'IL', true, now()),
  ('יואש', 'male', 'עברית', 'יואש', 'he', 'IL', true, now()),
  ('ירדן', 'male', 'עברית', 'ירדן', 'he', 'IL', true, now()),
  ('ירם', 'male', 'עברית', 'ירם', 'he', 'IL', true, now()),
  ('ים', 'male', 'עברית', 'ים', 'he', 'IL', true, now()),
  ('ארי', 'male', 'עברית', 'ארי', 'he', 'IL', true, now()),
  ('אליעזר', 'male', 'עברית', 'אליעזר', 'he', 'IL', true, now()),
  ('מיתר', 'male', 'עברית', 'מיתר', 'he', 'IL', true, now()),
  ('מירום', 'male', 'עברית', 'מירום', 'he', 'IL', true, now()),
  
  -- Hebrew girls names with Hebrew characters  
  ('שרה', 'female', 'עברית', 'נסיכה', 'he', 'IL', true, now()),
  ('מרים', 'female', 'עברית', 'ים המרירות', 'he', 'IL', true, now()),
  ('רחל', 'female', 'עברית', 'רחל', 'he', 'IL', true, now()),
  ('רבקה', 'female', 'עברית', 'לכרוך', 'he', 'IL', true, now()),
  ('חנה', 'female', 'עברית', 'חן', 'he', 'IL', true, now()),
  ('לאה', 'female', 'עברית', 'עייפה', 'he', 'IL', true, now()),
  ('רות', 'female', 'עברית', 'חברה', 'he', 'IL', true, now()),
  ('אסתר', 'female', 'עברית', 'כוכב', 'he', 'IL', true, now()),
  ('אביגיל', 'female', 'עברית', 'שמחת האב', 'he', 'IL', true, now()),
  ('נעמי', 'female', 'עברית', 'נעימה', 'he', 'IL', true, now()),
  ('טליה', 'female', 'עברית', 'טל אלוהים', 'he', 'IL', true, now()),
  ('טובה', 'female', 'עברית', 'טובה', 'he', 'IL', true, now()),
  ('טל', 'female', 'עברית', 'טל', 'he', 'IL', true, now()),
  ('נועה', 'female', 'עברית', 'תנועה', 'he', 'IL', true, now()),
  ('מיה', 'female', 'עברית', 'מים', 'he', 'IL', true, now()),
  ('עדי', 'female', 'עברית', 'תכשיט', 'he', 'IL', true, now()),
  ('שירה', 'female', 'עברית', 'שיר', 'he', 'IL', true, now()),
  ('תמר', 'female', 'עברית', 'תמר', 'he', 'IL', true, now()),
  ('יעל', 'female', 'עברית', 'יעל', 'he', 'IL', true, now()),
  ('עדינה', 'female', 'עברית', 'עדינה', 'he', 'IL', true, now()),
  ('אביגיל', 'female', 'עברית', 'שמחת האב', 'he', 'IL', true, now()),
  ('חן', 'female', 'עברית', 'חן', 'he', 'IL', true, now()),
  ('דנה', 'female', 'עברית', 'דנה', 'he', 'IL', true, now()),
  ('אפרת', 'female', 'עברית', 'אפרת', 'he', 'IL', true, now()),
  ('גלי', 'female', 'עברית', 'הגל שלי', 'he', 'IL', true, now()),
  ('הילה', 'female', 'עברית', 'הילה', 'he', 'IL', true, now()),
  ('אירית', 'female', 'עברית', 'אירית', 'he', 'IL', true, now()),
  ('קרן', 'female', 'עברית', 'קרן', 'he', 'IL', true, now()),
  ('ליאורה', 'female', 'עברית', 'האור שלי', 'he', 'IL', true, now()),
  ('מיכל', 'female', 'עברית', 'מי כמוני אלוהים', 'he', 'IL', true, now()),
  ('נוגה', 'female', 'עברית', 'נוגה', 'he', 'IL', true, now()),
  ('אורלי', 'female', 'עברית', 'האור שלי', 'he', 'IL', true, now()),
  ('רוני', 'female', 'עברית', 'השמחה שלי', 'he', 'IL', true, now()),
  ('סיון', 'female', 'עברית', 'סיון', 'he', 'IL', true, now()),
  ('יפה', 'female', 'עברית', 'יפה', 'he', 'IL', true, now()),
  ('הוה', 'female', 'עברית', 'הוה', 'he', 'IL', true, now()),
  ('אלה', 'female', 'עברית', 'אלה', 'he', 'IL', true, now()),
  ('מגי', 'female', 'עברית', 'מגי', 'he', 'IL', true, now()),
  ('דינה', 'female', 'עברית', 'דינה', 'he', 'IL', true, now()),
  ('תאיה', 'female', 'עברית', 'תאיה', 'he', 'IL', true, now()),
  ('מי', 'female', 'עברית', 'מי', 'he', 'IL', true, now()),
  ('נוי', 'female', 'עברית', 'נוי', 'he', 'IL', true, now()),
  ('אורה', 'female', 'עברית', 'אורה', 'he', 'IL', true, now()),
  ('מור', 'female', 'עברית', 'מור', 'he', 'IL', true, now()),
  ('מיכה', 'female', 'עברית', 'מיכה', 'he', 'IL', true, now()),
  ('עדוה', 'female', 'עברית', 'עדוה', 'he', 'IL', true, now()),
  ('יוליה', 'female', 'עברית', 'יוליה', 'he', 'IL', true, now()),
  ('אורי', 'female', 'עברית', 'אורי', 'he', 'IL', true, now()) ON CONFLICT (name, gender, language, region) DO NOTHING;
