-- Insert Hebrew names from the hebrewNamesClean.ts data
INSERT INTO public.names (name, gender, origin, meaning, language, region, is_active, created_at)
SELECT * FROM (
  VALUES 
    -- Hebrew boys names
    ('David', 'male', 'עברית', 'אהוב', 'he', 'IL', true, now()),
    ('Daniel', 'male', 'עברית', 'אלוהים הוא השופט שלי', 'he', 'IL', true, now()),
    ('Michael', 'male', 'עברית', 'מי כמוני אלוהים', 'he', 'IL', true, now()),
    ('Jonathan', 'male', 'עברית', 'אלוהים נתן', 'he', 'IL', true, now()),
    ('Joshua', 'male', 'עברית', 'אלוהים הוא ישועה', 'he', 'IL', true, now()),
    ('Benjamin', 'male', 'עברית', 'בן יד ימין', 'he', 'IL', true, now()),
    ('Samuel', 'male', 'עברית', 'נשמע על ידי אלוהים', 'he', 'IL', true, now()),
    ('Isaac', 'male', 'עברית', 'צחוק', 'he', 'IL', true, now()),
    ('Noah', 'male', 'עברית', 'מנוחה, נחמה', 'he', 'IL', true, now()),
    ('Tai', 'male', 'עברית', 'טל', 'he', 'IL', true, now()),
    ('Tahar', 'male', 'עברית', 'טוהר', 'he', 'IL', true, now()),
    ('Tuvi', 'male', 'עברית', 'טוב', 'he', 'IL', true, now()),
    ('Tuviya', 'male', 'עברית', 'אלוהים טוב', 'he', 'IL', true, now()),
    ('Tohar', 'male', 'עברית', 'טוהר', 'he', 'IL', true, now()),
    ('Tom', 'male', 'עברית', 'תמים', 'he', 'IL', true, now()),
    ('Tommy', 'male', 'עברית', 'תמים', 'he', 'IL', true, now()),
    ('Tim', 'male', 'עברית', 'שלמות', 'he', 'IL', true, now()),
    ('Timor', 'male', 'עברית', 'גבוה', 'he', 'IL', true, now()),
    ('Tal', 'male', 'עברית', 'טל', 'he', 'IL', true, now()),
    ('Talaor', 'male', 'עברית', 'טל אור', 'he', 'IL', true, now()),
    ('Tamir', 'male', 'עברית', 'נסתר', 'he', 'IL', true, now()),
    ('Yair', 'male', 'עברית', 'הוא יאיר', 'he', 'IL', true, now()),
    ('Yan', 'male', 'עברית', 'מתנת אלוהים', 'he', 'IL', true, now()),
    ('Yar', 'male', 'עברית', 'יער', 'he', 'IL', true, now()),
    ('Adam', 'male', 'עברית', 'אדם, אדמה', 'he', 'IL', true, now()),
    ('Eilan', 'male', 'עברית', 'עץ', 'he', 'IL', true, now()),
    ('Adel', 'male', 'עברית', 'אציל', 'he', 'IL', true, now()),
    ('Or', 'male', 'עברית', 'אור', 'he', 'IL', true, now()),
    ('Uri', 'male', 'עברית', 'האור שלי', 'he', 'IL', true, now()),
    ('Amit', 'male', 'עברית', 'ידיד', 'he', 'IL', true, now()),
    ('Ariel', 'male', 'עברית', 'אריה של אלוהים', 'he', 'IL', true, now()),
    ('Avi', 'male', 'עברית', 'אבי', 'he', 'IL', true, now()),
    ('Eli', 'male', 'עברית', 'האלוהים שלי', 'he', 'IL', true, now()),
    ('Gal', 'male', 'עברית', 'גל', 'he', 'IL', true, now()),
    ('Gil', 'male', 'עברית', 'שמחה', 'he', 'IL', true, now()),
    ('Omer', 'male', 'עברית', 'אלומה', 'he', 'IL', true, now()),
    ('Yuval', 'male', 'עברית', 'נחל', 'he', 'IL', true, now()),
    
    -- Hebrew girls names
    ('Sarah', 'female', 'עברית', 'נסיכה', 'he', 'IL', true, now()),
    ('Miriam', 'female', 'עברית', 'ים המרירות', 'he', 'IL', true, now()),
    ('Rachel', 'female', 'עברית', 'רחל', 'he', 'IL', true, now()),
    ('Rebecca', 'female', 'עברית', 'לכרוך', 'he', 'IL', true, now()),
    ('Hannah', 'female', 'עברית', 'חן', 'he', 'IL', true, now()),
    ('Leah', 'female', 'עברית', 'עייפה', 'he', 'IL', true, now()),
    ('Ruth', 'female', 'עברית', 'חברה', 'he', 'IL', true, now()),
    ('Esther', 'female', 'עברית', 'כוכב', 'he', 'IL', true, now()),
    ('Abigail', 'female', 'עברית', 'שמחת האב', 'he', 'IL', true, now()),
    ('Naomi', 'female', 'עברית', 'נעימה', 'he', 'IL', true, now()),
    ('Talia', 'female', 'עברית', 'טל אלוהים', 'he', 'IL', true, now()),
    ('Tova', 'female', 'עברית', 'טובה', 'he', 'IL', true, now()),
    ('Tal', 'female', 'עברית', 'טל', 'he', 'IL', true, now()),
    ('Noa', 'female', 'עברית', 'תנועה', 'he', 'IL', true, now()),
    ('Maya', 'female', 'עברית', 'מים', 'he', 'IL', true, now()),
    ('Adi', 'female', 'עברית', 'תכשיט', 'he', 'IL', true, now()),
    ('Shira', 'female', 'עברית', 'שיר', 'he', 'IL', true, now()),
    ('Tamar', 'female', 'עברית', 'תמר', 'he', 'IL', true, now()),
    ('Yael', 'female', 'עברית', 'יעל', 'he', 'IL', true, now()),
    ('Adina', 'female', 'עברית', 'עדינה', 'he', 'IL', true, now()),
    ('Avigail', 'female', 'עברית', 'שמחת האב', 'he', 'IL', true, now()),
    ('Chen', 'female', 'עברית', 'חן', 'he', 'IL', true, now()),
    ('Dana', 'female', 'עברית', 'דנה', 'he', 'IL', true, now()),
    ('Efrat', 'female', 'עברית', 'אפרת', 'he', 'IL', true, now()),
    ('Gali', 'female', 'עברית', 'הגל שלי', 'he', 'IL', true, now()),
    ('Hila', 'female', 'עברית', 'הילה', 'he', 'IL', true, now()),
    ('Irit', 'female', 'עברית', 'אירית', 'he', 'IL', true, now()),
    ('Keren', 'female', 'עברית', 'קרן', 'he', 'IL', true, now()),
    ('Liora', 'female', 'עברית', 'האור שלי', 'he', 'IL', true, now()),
    ('Michal', 'female', 'עברית', 'מי כמוני אלוהים', 'he', 'IL', true, now()),
    ('Noga', 'female', 'עברית', 'נוגה', 'he', 'IL', true, now()),
    ('Orli', 'female', 'עברית', 'האור שלי', 'he', 'IL', true, now()),
    ('Roni', 'female', 'עברית', 'השמחה שלי', 'he', 'IL', true, now()),
    ('Sivan', 'female', 'עברית', 'סיון', 'he', 'IL', true, now())
) AS v(name, gender, origin, meaning, language, region, is_active, created_at)
WHERE NOT EXISTS (
  SELECT 1 FROM public.names 
  WHERE names.name = v.name AND names.language = v.language AND names.region = v.region
) ON CONFLICT (name, gender, language, region) DO NOTHING;
